### ISSUE TITLE
egui image not loaded properly

### ISSUE THREAD

**Issue by james-ryans** [trevyn/egui-tetra2#1]
I'm trying to display an image to the egui window but the image didn't load properly, instead it shows list of bytes, even though I've followed all guides from the egui docs
1. Added egui_extras & image crate to Cargo.toml
```toml
[dependencies]
tetra = "0.8"
egui-tetra2 = "0.5"

egui_extras = { version = "0.28", features = ["all_loaders"] }
image = { version = "0.25", features = ["jpeg", "png"] }
```
2. Installed the image loaders
```rust
fn main() -> Result<(), Box<dyn error::Error>> {
    tetra::ContextBuilder::new("Experimental", WINDOW_WIDTH, WINDOW_HEIGHT)
        .timestep(time::Timestep::Fixed(TIMESTEP))
        .show_mouse(true)
        .build()?
        .run(|ctx| {
            let state_wrapper = egui_tetra2::StateWrapper::new(GameState::new(ctx)?);
            egui_extras::install_image_loaders(state_wrapper.ctx());

            Ok(state_wrapper)
        })
}
```
3. Showed the window in the UI function
```rust
    fn ui(
        &mut self,
        _ctx: &mut tetra::Context,
        egui_ctx: &egui::Context,
    ) -> Result<(), Box<dyn error::Error>> {
        let window = egui::Window::new("Image")
            .anchor(egui::Align2::RIGHT_TOP, emath::Vec2::new(-16.0, 16.0));

        window.show(egui_ctx, |ui| {
            ui.image(egui::include_image!("play-48.png"));
        });

        Ok(())
    }
```

I'm currently using egui-tetra2 "0.5" and tetra "0.8", and runs on macOS 12.5.1. Here's the screenshot of the issue:
<img width="381" alt="image" src="https://github.com/user-attachments/assets/4a5ecc72-42a9-4280-ae87-217c92a6aacc">

I've looked into egui images example and tried to run it. It ran normally on the same OS, the images displayed on the screen, and there was nothing fancy in the codes. Have you tried to display images with this library and encountered a similar issue? I've been stuck on this problem for hours and hoping for a solution or workaround.

**Comment by trevyn** [comment]
Looks like the integration wasn't bringing any egui textures other than the font atlas into tetra. Fixed this and published `egui-tetra2 = "0.5.1"`, and also added an egui image example that works for me. Please let me know if this works for you, thanks!
